#
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#    https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#    Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
#

---
name: "Run tests"
description: "Run tests and archive test results for subsequent publication"
inputs:
  command:
    required: true
    description: "The shell command to run tests"
runs:
  using: "composite"
  steps:
    - name: Run Tests
      shell: bash
      run: ${{ inputs.command }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test Results ${{ github.job }}
        path: |
          **/test-results/**/*.xml
          **/build/reports/jacoco/test/jacocoTestReport.xml
