#
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#    https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#    Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
#


---
name: "Bump version (manually)"

on:
  # can be called manually from GH webpage
  workflow_dispatch:
    inputs:
      target_branch:
        default: 'main'
        description: "Branch on which the version bump is to be done."
        required: false


jobs:
  Bump-Version:
    name: 'Update snapshot version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bump-version
        name: Bump version
        with:
          target_branch: ${{ inputs.target_branch }}